### ISSUE TITLE
Threads

### ISSUE THREAD

**Issue by omegasome** [Yakabuff/discord-dl#1]
Having checked, this doesn't download threads.

I'm not fluent in Go so I can't implement it myself. I haven't interacted with the threads part of the Discord API so I have no idea how easy or difficult it would be to fix.

**Comment by Yakabuff** [comment]
Hello, thanks for checking out my project. Unfortunately, discordgo has not implemented thread support yet and I would prefer to do API calls through the library.  https://github.com/bwmarrin/discordgo/pull/1058

When it is merged, I will implement it but keep in mind that it will likely involve breaking changes to the database.

**Comment by omegasome** [comment]
Excellent! Thank you _so much_ for this library; I've got a server with a large amount of information on it that I'd love to archive so it can be searched, and this is a lifesaver.

**Comment by Yakabuff** [comment]
Cool, let me know if you run into any unexpected behaviour or bugs

**Comment by omegasome** [comment]
Will do

**Comment by omegasome** [comment]
I don't wanna come across as entitled or anything, but I'm just wondering if this is coming along?

**Comment by Yakabuff** [comment]
Hi, just found out the threads feature was merged.  I'll start working on it after I finish refactoring

**Comment by Yakabuff** [comment]
Not sure if you're still interested but thread support has been added

**Comment by omegasome** [comment]
Yay! I found an alternative solution, but that solution doesn't give me a searchable database, so I definitely intend to use this as well.
